### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [kwwall/zaproxy-wki#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`Downloads.md`](https://github.com/kwwall/zaproxy-wki/blob/c311bf7aaa004d9bf863eff13b1333e2a5b6b99b/Downloads.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by kwwall** [comment]
Closed as per commit #45d6250
